{% set name = "qcat" %}
{% set version = "1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/szcompressor/qcat
  git_tag: f16032cf237837b1d32dde0c3daa6ad1ca4a912f

build:
  skip: True  # [win or osx]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - zstd

about:
  home: https://github.com/szcompressor/qcat
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Library to abstract between compressors and their configurations'
  description: |
    QCAT is a lightweight tool to analyze the data in the context of lossy compression. 
    You can   use it to change the size of data file in binary, convert binary data files to 
    texture files and vice versa. You can also plot the raw data file and decompressed data file 
    and visualize the difference by using the executable 'PlotSliceImage' for 2D and 3D datasets 
    in different directions.
  doc_url: https://robertu94.github.io/libpressio
  dev_url: https://github.com/robertu94/libpressio

extra:
  recipe-maintainers:
    - melchior
    - valmar
    - chrisvam
